# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
talosVersion: v1.11.0
kubernetesVersion: 1.34.0

clusterName: "homelab"
endpoint: https://10.252.252.199:6443

clusterPodNets: 
  - "10.244.0.0/16"

additionalApiServerCertSans: &sans
  - &kubeApiIP "10.252.252.199"
  - 127.0.0.1
additionalMachineCertSans: *sans 

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "control-01"
    ipAddress: "10.252.252.157"
    installDiskSelector:
      size: '> 4GB'
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:94:29:32"
        dhcp: false
        addresses:
          - "10.252.252.157/24"
        routes: &routes
          - network: 0.0.0.0/0
            gateway: "10.252.252.1"
        mtu: &mtu 1500
        vip: &vip
          ip: *kubeApiIP
  - hostname: "worker-01"
    ipAddress: "10.252.252.110"
    installDiskSelector:
      size: "> 4GB"
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:94:dd:be"
        dhcp: false
        addresses:
          - "10.252.252.110/24"
        routes: *routes
        mtu: *mtu
  - hostname: "worker-02"
    ipAddress: "10.252.252.111"
    installDiskSelector:
      size: "> 4GB"
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:94:f5:c5"
        dhcp: false
        addresses:
          - "10.252.252.111/24"
        routes: *routes
        mtu: *mtu
patches:
  - |-
    machine:
      network:
        nameservers:
          - 10.80.80.10
          - 10.80.80.11
  - "@./patches/global/cluster-discovery.yaml"
  - "@./patches/global/hostdns.yaml"
  - "@./patches/global/kubelet.yaml"
  - "@./patches/global/cni.yaml"
  - "@./patches/global/mayastor.yaml"
controlPlane:
  patches:
    - "@./patches/controller/api-access.yaml"
