apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SOME_SECRET: ENC[AES256_GCM,data:ZszdYouVDUJ+Aw==,iv:JHIg9yuHHbxlRuafCpU4ftIlKM8BiSLC3Vse077VavM=,tag:4re/f1sUQ6eErxeKeunYZw==,type:str]
sops:
  age:
    - recipient: age1gzp39gyv25y689qnwl74tuj5qls2g4zgu3rllf83syu9eveje37s3gdlq2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVkFxeWpXZURCb0N2TU1s
        YTdoZ2ZCc2VtQndRTmoyeVJ2cDVJSkNPcEFBClpaSDFwRUZrelpOZWNMT0R4TW1K
        OUdCU2k1K3hKOVcybGpFc0dtNDBYUlEKLS0tIGU4akJBdXZ4RHhOclY1ZGhBMFFi
        QzBBVTBUNWJ2WHFGa1ppRndVYjJCUUUKlsgAGTh4e87aWXdMPwavEbPcannZGnnt
        0RTUrDvUt8oXmtrazGxfjDW0+T2WVRII4516QwxeJK+c+y68N6sAQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T13:16:51Z"
  mac: ENC[AES256_GCM,data:6JcRQPZLheiz4vQqh2cKDqfWpzpb2aPSx90ykRnINmmeVDAjB2AY4WmPwo90Q9SewzzRKqMu+xNOb+c6iVGf4NywkQjQTlS1VkSwurVTszCEN6TlUuuGPTlLnZ58vuBmYduPmtdyQU9U5IJIwN6sJJbW9x1nfBj1DkC97nAa3dc=,iv:jUZklNi8e7TxYHPR2Scx3j1YpL0a7ErkAsDawGheFIA=,tag:roUkNnKIAql6qmbmvZrx8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
