apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Brussels
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "10.252.252.0/24"
  KUBE_VIP_ADDR: 10.252.252.199