apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SOME_SECRET: ENC[AES256_GCM,data:aFXrXzAMyjsPtSAWru30JiA=,iv:8EFjVAQkyNrgraP4MNuOf8mv6bdmj65olWIr3+ziPUo=,tag:/kRTrOum85PRiU4Mn2KF5g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15s5na3nnzeyvyc7defn92sg80nvt02usjyglgjjgk7xwsye79s3q39e7e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNko5K1BKY0dJY2VQVDd5
        SGtRbG5MQ0JWN0w4RXBDbHh1UzFZWk52eGkwCno5bzNvSVh3QVA2Z0d0WmFOczRE
        NkQ1SEJsMXNNaUk5M2dOMHhXcHZjNU0KLS0tIGJTK2FVMnduc0U4czBrUXhmc3pI
        YWVCZ21NaCtVVHVTcE5CUE5ia1Z0OXMK8F4S+u++r+MD+3aVbn5oc2IwX1kaOK79
        ZNVRT2bBEjvJLXZtHAiq6AR1g1zyp8uuvSx1y3vmPwUeEgEgUA5J0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T17:51:06Z"
  mac: ENC[AES256_GCM,data:Q49aC6rqN2XRtjCOCvlBDjmqH2R5xbKwTGb60uw4fIwp83e2w6xoW1vW20x6/Tx15B5QfCPtHo3UHgaPrhSipEVcIxBOsVaW2s+71cCtp8AUxQnb66501u7d0yDmsb3R7Z7Sp3tJeCFDO+NWQX68IYS9rzKcculMi+UFhvt+5YU=,iv:LCkxtkDS3nyf9HrVoeKGs1qNfmPFr9gVmxaC0hIlWyE=,tag:vNzrN5KOxrs0GreIq+9V7Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
