apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SOME_SECRET: ENC[AES256_GCM,data:OrSQ8v792HI4Gg==,iv:C6X2996qlwEvx0cEVBerDG8fp9nI5IOCRj6xAaNbdgg=,tag:tvTnOdFUEgl/Mn+Kk0WFbw==,type:str]
sops:
  age:
    - recipient: age1rf27l7lxj2dd78ah4nqv63ezqm5l2zlwzlqjx4y05pnvfy5tsu6s6ye0e6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdTBGYUFhY25sMVpORlBL
        ckN0YS83QkFmdEpTZTRDVGxWZE5TM3hPOFRRCitvcnpoeEZhSVYzVHZxNkJtRWRN
        QzBNWHpaYnNYMWxmU2VRSGhGM2c2T0kKLS0tIGswUkpyNTFPYkd3S1lTVlV6QXV5
        RElkOXYxYi9QdHRRM0lncHQzV3JmZ28KtF/yI0vvylnH2U9ZIvrjhs+qh/VSL8I/
        pbtslKmJXYSxMkfzwcQGC9Fr93N2ywYkBUyYRN0DvkYB2i589iMH0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T12:31:06Z"
  mac: ENC[AES256_GCM,data:f/bWh41COhxivtoZ01kVq9RYFBj7gtU7sh1npS2EKV+3EUkpYdpLx3Xi0usJ/eUZh/9EGBST8CLtAVZLxLJAveeOmhB253zkksk83y/KWWhFm9OZus+l0r/elzFuSo+NiMt74RigDIj7tkhmMCoMmmXmjS4a9cEbnRPi6AiA9do=,iv:Eohx/pZrt21IcC4G8XPY9zz6slq2HRj1KMusg7AAwyM=,tag:0tKT/TtimDcXZDO5z7/U6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
