apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SOME_SECRET: ENC[AES256_GCM,data:BrEEvyozfBOt+g==,iv:My9Q3abr7ISPizsUCx2CVHRypQ19qlHeKIHgyg1mggg=,tag:8nIihPKEwGw5mWnwfpkdOQ==,type:str]
sops:
  age:
    - recipient: age1rf27l7lxj2dd78ah4nqv63ezqm5l2zlwzlqjx4y05pnvfy5tsu6s6ye0e6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RzBvOElZWEx4eXlGMEV1
        aFp2aWU1RElMb1RjS0p0akFFQTN0UDVPdVZZCjZwclBOQ1dkeDhIK3dzYjJsRUkz
        RHhRVWpkdTFOMEZPUmt6NHQ1NTN5RGsKLS0tIGE4WEhMd1NQV1hVbUpRK1cvQjlq
        RTcyTnBnMXFOYUtCd0h5OFNPV2lkTVEKPHDNWT/DvIidIj+/a8fObGelTKrxNZMr
        HJPKq/tirZEjwj0M2b6/CphEpiE7J2Vs0VNMJYZhT49RfjomqQat3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T13:07:20Z"
  mac: ENC[AES256_GCM,data:QkADWrfqe0aRNdjAlS626LRi8zSF631npakPl8/RUDph695jio9DotxKFckUD7IvJZp+jHH/RcWPRBHUx+IlNWuzR4pOwh76XNpHAMLNEEgdZI7qopthIuU3d7arlNJbcxdpDV0tFoScrMhNovox4wNnrxpe1v2kjuIbIpkIxJU=,iv:Q3HPPJe3D3963gIeOgegw6Ya72DMZv/MXEPnYbVC9cU=,tag:8gPZdsfgN/G6z3wSql51dA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
