apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  ./helmrelease.yaml
configMapGenerator:
  - name: longhorn-helm-values
    files:
      - values.yaml=./helm-values.yaml
generatorOptions:
  disableNameSuffixHash: true

