apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: mayastor-helm-values
    files:
      - values.yaml=./helm-values.yaml
generatorOptions:
  disableNameSuffixHash: true
